// Role: the math kernel reference tables, generated from its config. KINDS are the adopted common kinds plus the local kinds; SOURCES is the config's source table; ADOPTED names the shared common kinds this kernel pins and ADOPTED_HASHES freezes the pinned type-hashes at adoption.
// Contract: exports KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK. Pure data; imports nothing.
// Invariant: the adopted hashes are frozen from corpora/_shared/common-types.js at generation; the real check verifies they still match the shared subtree, so a stale pin is caught.
// GENERATED by scaffolder/new-kernel.mjs from a kernel config; do not hand-edit.
"use strict";

const KINDS = [
  {
    "kind": "declaration",
    "ceiling": "constitutive"
  },
  {
    "kind": "measurement",
    "ceiling": "checked"
  },
  {
    "kind": "theorem",
    "ceiling": "constitutive"
  }
];

const SOURCES = [
  {
    "source_id": "src:confidence-order",
    "source_class": "institutional-report",
    "description": "The EpiStack confidence order and protocol specification (kernel/schema/confidence.mjs, docs/protocol-spec.md Section 3): the grade set, its partial order, and the empirical/constitutive mode split, declared as this kernel's given primitives"
  },
  {
    "source_id": "src:exhaustion",
    "source_class": "primary-measurement",
    "description": "PLACEHOLDER CLASS (source-class decision, case b): exhaustive enumeration of a finite operation over its whole domain, a proof by exhaustion. The substrate menu has no exhaustive-check class; primary-measurement is the closest honest existing class pending a maintainer decision on whether the substrate menu gains one"
  },
  {
    "source_id": "src:differential-test",
    "source_class": "primary-measurement",
    "description": "PLACEHOLDER CLASS (source-class decision, case b): a differential-test harness that generates random graphs and confirms the extracted math is what the code computes. The substrate menu has no differential-testing class; primary-measurement is the closest honest existing class pending a maintainer decision"
  },
  {
    "source_id": "src:formal-proof",
    "source_class": "primary-measurement",
    "description": "PLACEHOLDER CLASS (source-class decision, case b): a formal proof-assistant proof. The substrate menu has no formal-proof class; primary-measurement is the closest honest existing class pending a maintainer decision, and it is the least natural fit of the three placeholders"
  }
];

// the shared common kinds this kernel adopts (names), and the type-hashes pinned at adoption.
const ADOPTED = [
  "declaration",
  "measurement"
];
const ADOPTED_HASHES = {
  "declaration": "354cba45e263a9788064fbf35d71d8506dd93ddf8c35b092ba606e5c2cc3b1bd",
  "measurement": "2ed60a0154fef12d5d630f4a3f52d06686479c75aa57a44fd3b1488d581d3621"
};

// time-lock and standing (F5): the one clean free parameter, no grounding consequence.
const TIME_LOCK = {
  "setting": "light"
};

module.exports = { KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK };
