// Role: the floor. Named standard transformations, the coordinate basis. Each is a leaf
//   that cites its proof and is never re-derived in the engine (T1-2). Shared across the
//   DAG: a primitive has many parents, which is how branches "share a basis".
// Contract: exports { id -> primitive node } conforming to data/schema.js (kind primitive).
// Invariant: pure data. A primitive carries a citation and no children. If one grows an
//   implementation it has stopped being a primitive (exclusion reservoir).
"use strict";

const PRIMITIVES = {
  // -- population-pipeline floor (docs/population-pipeline.md) --
  "prim.estimator": {
    id: "prim.estimator",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Summary statistic",
    role: "compute a summary statistic from a sample",
    math: "T = f({x_i})",
    formal_status: "nl",
    children: [],
    citation: { source: "standard estimation theory", target: "textbook" },
    // shared leaf: parent of both pipeline stages (one node, two parents)
    parents: ["pipe.stage1", "pipe.stage2"],
  },
  "prim.exchangeability": {
    id: "prim.exchangeability",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Exchangeability / selection",
    role: "the condition that sample inclusion is independent of the estimand",
    math: "P(include | x) = const",
    formal_status: "nl",
    children: [],
    citation: { source: "exchangeability / selection-bias, standard", target: "textbook" },
    parents: ["pipe.stage1"],
  },
  "prim.sufficiency": {
    id: "prim.sufficiency",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Sufficiency",
    role: "the relation between a statistic and the information it retains about a parameter",
    math: "T sufficient for theta iff P(x | T, theta) = P(x | T)",
    formal_status: "nl",
    children: [],
    citation: { source: "sufficiency / Fisher-Neyman factorization", target: "textbook" },
    parents: ["pipe.stage2"],
  },

  // -- LHC Branch 2 floor (docs/lhc-cascade.md) --
  "prim.lorentz-boost": {
    id: "prim.lorentz-boost",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Lorentz boost",
    role: "convert a center-of-mass velocity to the lab frame",
    math: "beta_lab from the CoM-to-lab boost",
    formal_status: "typed",
    children: [],
    citation: { source: "Lorentz boost; standard relativistic kinematics", target: "Mathlib / PDG" },
    parents: ["lhc.N2.1"],
  },
  "prim.bethe-bloch": {
    id: "prim.bethe-bloch",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Bethe-Bloch stopping power",
    role: "electromagnetic energy loss per length for a charged projectile in matter",
    math: "-dE/dx (charged), Bethe-Bloch",
    formal_status: "typed",
    children: [],
    citation: { source: "Bethe-Bloch stopping-power integral", target: "PDG" },
    parents: ["lhc.N2.2"],
  },
  "prim.geometric-capture": {
    id: "prim.geometric-capture",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Geometric / gravitational capture",
    role: "energy loss by capture for a neutral object, far weaker, density-gated",
    math: "-dE/dx (neutral), geometric capture cross-section",
    formal_status: "nl",
    children: [],
    citation: { source: "geometric capture; gravitational stopping", target: "Giddings-Mangano arXiv:0806.3381" },
    parents: ["lhc.N2.2"],
  },

  // -- LHC Branch 1 floor (production; docs/lhc-cascade.md) --
  "prim.mandelstam-s": {
    id: "prim.mandelstam-s",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Mandelstam s (fixed-target)",
    role: "the center-of-mass energy squared for a projectile on a stationary target",
    math: "s = 2 E_cr m_N + m_N^2 + m_cr^2  (fixed target)",
    formal_status: "typed",
    children: [],
    citation: { source: "Mandelstam invariants; fixed-target kinematics", target: "PDG" },
    parents: ["lhc.N1.1"],
  },
  "prim.cosmic-ray-flux": {
    id: "prim.cosmic-ray-flux",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Cosmic-ray flux spectrum",
    role: "the measured differential flux of cosmic rays as a function of energy",
    math: "Phi(E) = dN / (dA dt dOmega dE)",
    formal_status: "nl",
    children: [],
    citation: { source: "cosmic-ray flux spectrum, measured", target: "PDG / Pierre Auger" },
    parents: ["lhc.N1.2"],
  },
  "prim.interaction-rate": {
    id: "prim.interaction-rate",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Interaction-rate integral",
    role: "the count of interactions as flux times target number times exposure",
    math: "N = (area x time) x integral Phi(E) n_target dE",
    formal_status: "typed",
    children: [],
    citation: { source: "interaction rate = flux x number density x exposure", target: "textbook" },
    parents: ["lhc.N1.2"],
  },
  "prim.production-rate": {
    id: "prim.production-rate",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Production count from cross-section",
    role: "events produced equal collisions times the production cross-section, the same model on any side",
    math: "N_BH = N_coll x sigma_BH",
    formal_status: "typed",
    children: [],
    citation: { source: "production count = luminosity (or collisions) x cross-section, standard", target: "PDG" },
    parents: ["lhc.N1.3"],
  },

  // -- LHC Branch 3 floor (accretion; docs/lhc-cascade.md). Read from Giddings-Mangano
  //    (arXiv:0806.3381), NOT reconstructed from a generic Bondi form: the rate is piecewise
  //    and departs from naive four-dimensional Bondi three ways (regime, D-dimensional radius,
  //    nuclear-matter collapse). Each leaf cites the governing G-M equation or section. --
  "prim.gm-master-rate": {
    id: "prim.gm-master-rate",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Accretion master law (capture radius)",
    role: "the accretion rate is the flux through the capture radius, distinct from the Schwarzschild radius",
    math: "dM/dt = pi r_c^2 F  (G-M 4.1);  F velocity- or Fermi-driven (4.2, 4.3);  r_c != R (4.4)",
    formal_status: "typed",
    children: [],
    citation: { source: "accretion master law dM/dt = pi r_c^2 F, capture radius r_c distinct from Schwarzschild R (eqs 4.1-4.4)", target: "Giddings-Mangano arXiv:0806.3381" },
    parents: ["lhc.N3.1"],
  },
  "prim.gm-em-capture": {
    id: "prim.gm-em-capture",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Subatomic electromagnetic-capture rate",
    role: "below the crossover mass the rate is set by electromagnetic capture, not Bondi",
    math: "dM/dt = pi rho v R_EM^2  (G-M 4.19),  R_EM from (4.10);  governs for M < M_{a,D}",
    formal_status: "typed",
    children: [],
    citation: { source: "electromagnetic-capture regime dM/dt = pi rho v R_EM^2 (eq 4.19), capture radius R_EM (eq 4.10)", target: "Giddings-Mangano arXiv:0806.3381" },
    parents: ["lhc.N3.1"],
  },
  "prim.gm-crossover-mass": {
    id: "prim.gm-crossover-mass",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Capture-regime crossover mass",
    role: "the mass at which accretion crosses from the subatomic electromagnetic law to macroscopic Bondi",
    math: "M_{a,D}  (G-M 4.35):  below it electromagnetic capture governs, above it Bondi governs",
    formal_status: "typed",
    children: [],
    citation: { source: "crossover mass M_{a,D} separating the electromagnetic-capture and Bondi regimes (eq 4.35)", target: "Giddings-Mangano arXiv:0806.3381" },
    parents: ["lhc.N3.1"],
  },
  "prim.gm-bondi-ddim": {
    id: "prim.gm-bondi-ddim",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "D-dimensional Bondi rate",
    role: "the macroscopic regime is Bondi with the D-dimensional Bondi radius, not the four-dimensional reference form",
    math: "dM/dt = pi lambda_D c_s R_B^2 rho  (G-M 4.31);  R_B = [(D-3)/(4 c_s^2)]^{1/(D-3)} R  (4.32);  3 < lambda_D < 18",
    formal_status: "typed",
    children: [],
    citation: { source: "D-dimensional Bondi regime dM/dt = pi lambda_D c_s R_B^2 rho (eq 4.31) with the D-dimensional Bondi radius (eq 4.32), 3 < lambda_D < 18", target: "Giddings-Mangano arXiv:0806.3381" },
    parents: ["lhc.N3.1"],
  },
  "prim.gm-geometric-rate": {
    id: "prim.gm-geometric-rate",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Nuclear-matter geometric rate",
    role: "in a neutron star there are no atoms, so the atomic phases collapse to one nucleon-scale phase and the rate is geometric",
    math: "dM/dt = pi rho R^2  (G-M 8.10) = (4.31) with c_s = 1, lambda_D = 1, R_B -> R;  r_c >~ r_N",
    formal_status: "typed",
    children: [],
    citation: { source: "neutron-star nuclear-matter geometric law dM/dt = pi rho R^2 (eq 8.10), atomic phases collapsed to one nucleon-scale phase (Section 8.2.2)", target: "Giddings-Mangano arXiv:0806.3381" },
    parents: ["lhc.N3.1"],
  },
  "prim.gm-destroy-integral": {
    id: "prim.gm-destroy-integral",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Piecewise destroy-time integral",
    role: "the time to consume the body is the accretion integral, evaluated piecewise across the regimes",
    math: "t_destroy = integral dM / (dM/dt),  piecewise  (G-M 4.39-4.41 via the Bondi radius; neutron-star analogue 8.11)",
    formal_status: "typed",
    children: [],
    citation: { source: "destroy-time integral t = integral dM/(dM/dt) evaluated piecewise across the regimes (eqs 4.39-4.41; neutron-star analogue eq 8.11)", target: "Giddings-Mangano arXiv:0806.3381" },
    parents: ["lhc.N3.2"],
  },
  "prim.gm-wd-destroytime": {
    id: "prim.gm-wd-destroytime",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "White-dwarf destruction time",
    role: "the longest unwarped white-dwarf destruction time, far below observed white-dwarf ages",
    math: "t_WD <= 80 Myr (longest unwarped D=7; G-M 7.7-7.12);  t_Earth/t_WD ~ 1.9 x 10^4 (7.15)",
    formal_status: "typed",
    children: [],
    citation: { source: "white-dwarf destruction time <= 80 Myr for the longest unwarped D=7 phase (eqs 7.7-7.12), general relation t_Earth/t_WD ~ 1.9e4 (eq 7.15)", target: "Giddings-Mangano arXiv:0806.3381" },
    parents: ["lhc.N3.2"],
  },
  "prim.gm-ns-destroytime": {
    id: "prim.gm-ns-destroytime",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Neutron-star destruction time",
    role: "the neutron-star destruction time once the hole reaches the core, far below observed neutron-star ages",
    math: "t_NS <~ 50 yr (D <= 7), up to ~10 Myr (D = 11);  rate-limited by production + crust penetration (G-M 8.2.1, 8.2.2)",
    formal_status: "typed",
    children: [],
    citation: { source: "neutron-star destruction time <~ 50 yr for D <= 7, up to ~10 Myr for D = 11, rate-limited by production and crust penetration (Sections 8.2.1, 8.2.2)", target: "Giddings-Mangano arXiv:0806.3381" },
    parents: ["lhc.N3.2"],
  },
  "prim.gm-exclusion": {
    id: "prim.gm-exclusion",
    kind: "primitive",
    presentation: { type: "primitive" },
    label: "Stable-hole exclusion bound",
    role: "the survival of the dense bodies excludes a dangerously accreting stable black hole",
    math: "stable black holes ruled out for crossover radius R_C >~ 15 Angstrom  (G-M Section 9)",
    formal_status: "typed",
    children: [],
    citation: { source: "exclusion of stable black holes for crossover radius R_C >~ 15 Angstrom, from the survival of white dwarfs and neutron stars (Section 9)", target: "Giddings-Mangano arXiv:0806.3381" },
    parents: ["lhc.N3.2"],
  },
};

if (typeof module !== "undefined" && module.exports) module.exports = { PRIMITIVES };
