// Role: the first scaffolder step. Reads a kernel config (scaffolder/kernel-config.schema.json shape)
//   and emits a working empty kernel under corpora/<kernel_id>/ plus a build/<id>-build.mjs and
//   build/check-<id>.mjs modeled on the covid pattern, then runs the generated check and reports. The
//   scaffolder is dumb: it emits files and checks only well-formedness; all rule-checking is deferred to
//   the real gate and the real check it runs, so an unadopted type or a bad source class fails loudly in
//   the check, not here.
// Contract: `node scaffolder/new-kernel.mjs <config.json> [--clean]`. Emits into the repo tree (so the
//   generated build files reach the kernel through ../kernel), runs build/check-<id>.mjs, and exits with
//   its code. --clean removes the generated files after checking (for demos that must leave no residue).
// Invariant: the generator holds no copy of the kernel's rules. It bakes adopted type-hashes from the
//   shared subtree at generation time (adoption pins the hash and freezes meaning), and emits whatever
//   the config declares; the real check is the enforcer.
"use strict";
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const { COMMON_BUNDLES, COMMON_TYPE_HASHES } = require(join(ROOT, "corpora/_shared/common-types.js"));

const args = process.argv.slice(2);
const clean = args.includes("--clean");
const configPath = args.find((a) => !a.startsWith("--"));
if (!configPath) { console.error("usage: node scaffolder/new-kernel.mjs <config.json> [--clean]"); process.exit(2); }

// ---- read the config; check only well-formedness, never the kernel's rules ----
const config = JSON.parse(readFileSync(resolve(configPath), "utf8"));
for (const f of ["kernel_id", "adopted_type_hashes", "sources"]) {
  if (!(f in config)) { console.error(`config is not well-formed: missing required field '${f}'`); process.exit(2); }
}
const id = config.kernel_id;
if (!/^[a-z0-9][a-z0-9-]*$/.test(id)) { console.error(`config is not well-formed: kernel_id '${id}' is not a safe id`); process.exit(2); }
const adopted = config.adopted_type_hashes || [];
const localKinds = config.local_kinds || [];
const sources = config.sources || [];
const timeLock = config.time_lock || { setting: "light" };

// ---- the adopted kind rows: pull the ceiling from the shared bundle; bake the pinned hash. A name not
// in the shared subtree resolves to no row and no hash, and the real check flags it. ----
const adoptedRows = [];
const adoptedHashes = {};
for (const name of adopted) {
  if (COMMON_BUNDLES[name]) { adoptedRows.push({ kind: name, ceiling: COMMON_BUNDLES[name].ceiling }); adoptedHashes[name] = COMMON_TYPE_HASHES[name]; }
}
const kindRows = adoptedRows.concat(localKinds.map((k) => ({ kind: k.kind, ceiling: k.ceiling })));

const J = (v) => JSON.stringify(v, null, 2);
const head = (role, contract, invariant) => `// Role: ${role}\n// Contract: ${contract}\n// Invariant: ${invariant}\n// GENERATED by scaffolder/new-kernel.mjs from a kernel config; do not hand-edit.\n"use strict";\n`;

// ---- emit corpora/<id>/tables.js (pure data, imports nothing) ----
const corpusDir = join(ROOT, "corpora", id);
const buildDir = join(ROOT, "build");
mkdirSync(corpusDir, { recursive: true });

const tablesSrc = head(
  `the ${id} kernel reference tables, generated from its config. KINDS are the adopted common kinds plus the local kinds; SOURCES is the config's source table; ADOPTED names the shared common kinds this kernel pins and ADOPTED_HASHES freezes the pinned type-hashes at adoption.`,
  `exports KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK. Pure data; imports nothing.`,
  `the adopted hashes are frozen from corpora/_shared/common-types.js at generation; the real check verifies they still match the shared subtree, so a stale pin is caught.`
) +
`\nconst KINDS = ${J(kindRows)};\n\nconst SOURCES = ${J(sources)};\n\n// the shared common kinds this kernel adopts (names), and the type-hashes pinned at adoption.\nconst ADOPTED = ${J(adopted)};\nconst ADOPTED_HASHES = ${J(adoptedHashes)};\n\n// time-lock and standing (F5): the one clean free parameter, no grounding consequence.\nconst TIME_LOCK = ${J(timeLock)};\n\nmodule.exports = { KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK };\n`;
writeFileSync(join(corpusDir, "tables.js"), tablesSrc);

// ---- emit corpora/<id>/<id>-data.js (the empty claims-and-links skeleton) ----
const dataSrc = head(
  `the ${id} kernel store skeleton: an empty claims-and-links data file the author fills. Generated empty by the scaffolder.`,
  `exports STORE = { store_id, claims, links }. Pure data; imports nothing.`,
  `zero claims and zero links; a complete empty kernel that the gate accepts.`
) + `\nconst STORE = { store_id: ${J(id)}, claims: [], links: [] };\n\nmodule.exports = { STORE };\n`;
writeFileSync(join(corpusDir, `${id}-data.js`), dataSrc);

// ---- emit build/<id>-build.mjs (modeled on build/covid-build.mjs) ----
const buildSrc = `// Role: the generated builder for the ${id} kernel: builds its v3 store through the real gate from
//   the pure data in corpora/${id}, exactly as build/covid-build.mjs builds covid.
// Contract: buildKernel() -> { store_id, tables, claims, refId, state, view, receipt }. Imports the
//   kernel and corpora/${id}; pure over the corpus.
// Invariant: grades are the kernel's own derivation; the scaffolder adds no rule of its own.
// GENERATED by scaffolder/new-kernel.mjs; do not hand-edit.
"use strict";
import { createRequire } from "node:module";
import { claimRecord, linkRecord } from "../kernel/schema/records.mjs";
import { makeSourceTable, makeKindTable } from "../kernel/schema/tables.mjs";
import { genesis } from "../kernel/store/state.mjs";
import { apply } from "../kernel/store/apply.mjs";
import { storeViewOf } from "../kernel/store/decay.mjs";
import { decide } from "../kernel/gate/gate.mjs";

const require = createRequire(import.meta.url);
const { KINDS, SOURCES } = require("../corpora/${id}/tables.js");
const { STORE } = require("../corpora/${id}/${id}-data.js");

export function buildKernel() {
  const tables = { sourceTable: makeSourceTable(SOURCES), kindTable: makeKindTable(KINDS) };
  const refId = new Map();
  const claims = STORE.claims.map((spec) => {
    const rec = claimRecord({ kind: spec.kind, statement: spec.statement, source_id: spec.source_id, contributor_id: spec.contributor_id, declared_grade: spec.declared_grade, checking_records: spec.checking_records, closing_condition: spec.closing_condition });
    refId.set(spec.ref, rec.identity);
    return { rec, spec };
  });
  const links = (STORE.links || []).map((l) => linkRecord({ link_kind: l.link_kind, from_identity: refId.get(l.from), to_identity: refId.get(l.to), support_group: l.support_group, source_id: l.source_id, contributor_id: l.contributor_id, declared_grade: l.declared_grade }));
  const entries = claims.map((c) => c.rec);
  const state = apply(genesis(), { entries, links, applied_contribution_hash: STORE.store_id, receipt_reference: STORE.store_id });
  const view = storeViewOf(state, tables);
  const receipt = decide({ hash: STORE.store_id, entries, links }, storeViewOf(genesis(), tables), {});
  return { store_id: STORE.store_id, tables, claims, refId, state, view, receipt };
}
`;
writeFileSync(join(buildDir, `${id}-build.mjs`), buildSrc);

// ---- emit build/check-<id>.mjs (the real check: adopted hashes valid, tables build, gate accepts) ----
const checkSrc = `// Role: the generated oracle for the ${id} kernel. Verifies the config produced a coherent empty
//   kernel: every adopted kind is in the shared subtree and its pinned hash matches, the source table
//   and kind table build (the real kernel throws on a bad source class or ceiling), and the gate accepts
//   the empty store. The scaffolder holds no rules; this check is the real enforcer.
// Contract: \`node build/check-${id}.mjs\` exits non-zero on any failure.
// Invariant: zero claims, but the adopted hashes, the tables, and the gate decision are all real.
// GENERATED by scaffolder/new-kernel.mjs; do not hand-edit.
"use strict";
import { createRequire } from "node:module";
import { hashTypeBundle } from "../kernel/schema/type-hash.mjs";

const require = createRequire(import.meta.url);
const { KINDS, SOURCES, ADOPTED, ADOPTED_HASHES } = require("../corpora/${id}/tables.js");
const { COMMON_TYPE_HASHES } = require("../corpora/_shared/common-types.js");

let fails = 0;
const ok = (c, m) => { console.log(\`\${c ? "  ok  " : " FAIL "} \${m}\`); if (!c) fails++; };
const H = "=".repeat(80);
console.log(H); console.log("CHECK-${id.toUpperCase()} (generated): a coherent empty kernel"); console.log(H);

console.log("\\n[1] every adopted kind is in the shared subtree and its pinned hash matches");
for (const name of ADOPTED) {
  const shared = COMMON_TYPE_HASHES[name];
  ok(shared !== undefined, \`adopts common kind '\${name}', which is present in the shared subtree\`);
  if (shared !== undefined) {
    ok(ADOPTED_HASHES[name] === shared, \`the pinned hash for '\${name}' still matches the shared subtree\`);
    const row = KINDS.find((k) => k.kind === name);
    ok(!!row && hashTypeBundle({ kind: row.kind, ceiling: row.ceiling, compatibility_rule_id: null, atlas_refs: [] }) === shared, \`the '\${name}' kind row implies the adopted hash\`);
  }
}

console.log("\\n[2] the source table and kind table build, and the gate accepts the empty store");
let built = null;
try {
  const mod = await import("./${id}-build.mjs");
  built = mod.buildKernel();
  ok(true, "the kernel builds: source table, kind table, and the empty store all valid");
} catch (e) {
  ok(false, \`the kernel fails to build: \${e.message}\`);
}
if (built) {
  ok(built.state.entries.length === 0, \`the empty kernel has zero claims (got \${built.state.entries.length})\`);
  ok(built.receipt.decision === "accepted", \`the empty contribution is accepted by the real gate (got \${built.receipt.decision})\`);
}

console.log("\\n" + H);
if (fails === 0) console.log("verified: the config produced a coherent empty ${id} kernel; adopted hashes valid, tables built, gate accepts.");
console.log(fails === 0 ? "check-${id}: OK" : \`check-${id}: \${fails} FAILURE(S)\`);
console.log(H);
process.exit(fails === 0 ? 0 : 1);
`;
writeFileSync(join(buildDir, `check-${id}.mjs`), checkSrc);

const emitted = [`corpora/${id}/tables.js`, `corpora/${id}/${id}-data.js`, `build/${id}-build.mjs`, `build/check-${id}.mjs`];
console.log(`generated ${id}: ${emitted.join(", ")}`);

// ---- generate-then-check: run the real check and report ----
console.log(`\nrunning build/check-${id}.mjs (the real check over the generated kernel):\n`);
let code = 0;
try {
  const out = execFileSync("node", [join(buildDir, `check-${id}.mjs`)], { cwd: ROOT, encoding: "utf8" });
  process.stdout.write(out);
} catch (e) {
  if (e.stdout) process.stdout.write(e.stdout);
  if (e.stderr) process.stderr.write(e.stderr);
  code = e.status || 1;
}

if (clean) {
  rmSync(corpusDir, { recursive: true, force: true });
  for (const f of [`${id}-build.mjs`, `check-${id}.mjs`]) { const p = join(buildDir, f); if (existsSync(p)) rmSync(p); }
  console.log(`\ncleaned generated files for ${id}`);
}

console.log(`\nnew-kernel: ${code === 0 ? "the generated kernel passed its check" : "the generated kernel FAILED its check (see the named cause above)"}`);
process.exit(code);
